/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: david.campuzano (https://sketchfab.com/david.campuzano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hacker-room-stylized-a0cfe6edf2dd494c8a95addf6bb13a10
Title: Hacker Room - Stylized
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'

export default function HackerRoom(props) {
  const { scene } = useGLTF('/models/hacker-room.glb')
  const modelRef = useRef()
  const { onReady, rotationSpeed = 0.35, ...groupProps } = props

  useEffect(() => {
    onReady?.()
  }, [onReady])

  useFrame((_, delta) => {
    if (modelRef.current) {
      modelRef.current.rotation.y += delta * rotationSpeed
    }
  })

  return (
    <group ref={modelRef} {...groupProps} dispose={null}>
      <primitive object={scene} />
    </group>
  )
}

useGLTF.preload('/models/hacker-room.glb')
