
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export default function Space(props) {
  const { nodes, materials } = useGLTF('/models/need_some_space.glb')
  const spaceRef = useRef()

  useFrame(({ pointer }, delta) => {
    const targetRotationX = pointer.y * 0.2
    const targetRotationY = pointer.x * 0.35

    spaceRef.current.rotation.x +=
      (targetRotationX - spaceRef.current.rotation.x) * delta * 3
    spaceRef.current.rotation.y +=
      (targetRotationY - spaceRef.current.rotation.y) * delta * 3
  })

  return (
    <group ref={spaceRef} {...props} dispose={null}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  )
}

