
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import { useGLTF } from '../lib/useGLTF'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Space = (props) => {
  const { nodes, materials } = useGLTF('/models/need_some_space.glb')
  const spaceRef = useRef()

  // Create one looping tween for the model. Creating this inside useFrame
  // would create a new infinite tween on every rendered frame.
  useGSAP(() => {
    if (!spaceRef.current) return

    gsap.to(spaceRef.current.position, {
      x: 0.5,
      duration: 5,
      repeat: -0.05,
      yoyo: true,
      ease: 'power1.inOut',
    })
  }, { dependencies: [] })

  useFrame(({ pointer }, delta) => {
    if (!spaceRef.current) return

    const targetRotationX = pointer.y * 0.2
    const targetRotationY = pointer.x * 0.35

    spaceRef.current.rotation.x +=
      (targetRotationX - spaceRef.current.rotation.x) * delta * 3
    spaceRef.current.rotation.y +=
      (targetRotationY - spaceRef.current.rotation.y) * delta * 3
  })

  return (
    <group ref={spaceRef} {...props} dispose={null}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  )
}
export default Space
